services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 10s

  app:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      DATABASE_DSN: postgres://postgres:postgres@db:5432/movies?sslmode=disable
    restart: always