services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d movies" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./wait-for-db.sh db ./main
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: postgres
      ENV_DB_DSN: postgres://postgres:postgres@db:5432/movies?sslmode=disable
    ports:
      - "4000:4000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge